language: ruby
sudo: false
cache: bundler

rvm:
- 2.0.0
- 2.1.8
- 2.2.4

gemfile:
  - gemfiles/Gemfile.activerecord-4.0.x
  - gemfiles/Gemfile.activerecord-4.1.x
  - gemfiles/Gemfile.activerecord-4.2.x

env: DATABASE_URL=postgres://localhost/travis RUBYOPT=-W0

before_script:
- bundle exec rake db:migrate

addons:
  postgresql: '9.3'
